### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [eddex/jumpcutter-android#2]
Hi @eddex  , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by eddex** [comment]
Hi @zularizal 

Yes sure, feel free top contribute if you like!

Cheers

**Comment by Jackle1996** [comment]
Hi @zularizal 

We'll present the app in front of a big audiance next week.
If you want your logo to be part of this app, then please submit your logo till saturday evening.
This leaves us enough time to include your logo in our presentation/app.

Cheers

**Comment by zularizal** [comment]
Hello @Jackle1996  tomorrow or the day after, I will send the proposal logo

**Comment by zularizal** [comment]
Hi @eddex @Jackle1996 , here are some design logos for your project. The logos are inspired by a scissor, paper and film rolls, and a camera.
Which one do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/57920528-777bc000-78c5-11e9-8e89-d2126b8f232c.png)

**Comment by eddex** [comment]
Hi @zularizal

We think the red/orange logo (the top-middle one) looks best. Thanks for your efforts!

**Comment by zularizal** [comment]
Okay, I will make a pr

**Comment by zularizal** [comment]
Hi @eddex , I sent a pull request.

And also I have uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=1JB5GbEV6ySMbriUGwtOV2yv6LxPDs7Ma

**Comment by eddex** [comment]
The PR is merged. Thanks again for the great logo and also adding it to the app and readme! :)
