### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [eddex/jumpcutter-android#5]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by eddex** [comment]
Hi,

This project works as is but is far from great. The UI is not very beautiful (although it does the job), the server instance that is currently running is not online 24/7 and it's only a small server that can't handle more than a handful of users at the same time. 

I wouldn't consider it ready for publishing on F-Droid. If you like to do it anyways, you might want to setup a new server for the video processing.

Cheers,
eddex

**Comment by Poussinou** [comment]
Let's wait a little bit, I won't setup a new server for F-Droid community. But it could be of some interest for F-Droid users later.

Ping me one day if you consider it to be ready for F-Droid

**Comment by eddex** [comment]
Unfortunately I don't plan on investing any more time into this app. If you really want to see it in the F-Droid store, someone else would have to put some effort into this project.
